version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api4chatbot
    restart: unless-stopped
    ports:
      - "8005:8005"
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount config if needed
      - ./config:/app/config
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8005/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
