# Schema for Regulation/Policy Documents (Quy định, hướng dẫn)
document_type: regulation
description: "Schema for Vietnamese regulatory and policy documents with hierarchical structure"

# First-level chunking: Split by major sections/articles
first_level_boundaries:
  - type: chapter
    marker: "^Chương\\s+([IVX]+|\\d+)"
    keep_hierarchy: true

  - type: article
    marker: "^Điều\\s+\\d+"
    include_full_article: true

  - type: section
    marker: "^Mục\\s+\\d+"
    keep_hierarchy: true

  - type: heading
    marker: "^#{1,3}\\s+.*"
    levels: [1, 2, 3]

# Metadata fields for regulations
first_level_metadata_fields:
  - article_number      # "Điều 15"
  - chapter_number      # "Chương III"
  - section_number      # "Mục 2"
  - heading_path        # "Chương III > Mục 2 > Điều 15"
  - effective_date      # "2025-01-01"
  - amendment_info      # "Sửa đổi theo TT 45/2024"
  - scope               # "Áp dụng cho toàn quốc"
  - authority           # "Bộ Tài chính"
  - references          # ["Điều 10", "Nghị định 123"]
  - legal_basis         # "Căn cứ Luật..."

# Second-level decomposition
second_level_decomposition:
  article:
    - type: clause
      description: "Extract numbered clauses within articles"
      patterns:
        - "^\\d+\\.\\s+"     # 1. 2. 3.
        - "^Khoản\\s+\\d+"    # Khoản 1, Khoản 2

    - type: point
      description: "Extract lettered points"
      patterns:
        - "^[a-z]\\)\\s+"     # a) b) c)
        - "^Điểm\\s+[a-z]"    # Điểm a, Điểm b

    - type: definition
      description: "Extract definitions"
      patterns:
        - "là"
        - "có nghĩa là"
        - "được hiểu là"
        - "bao gồm"

    - type: condition
      description: "Extract conditional clauses"
      patterns:
        - "trong trường hợp"
        - "khi|nếu"
        - "trừ khi"
        - "với điều kiện"

  section:
    - type: subsection
      preserve_numbering: true

    - type: rule
      patterns:
        - "phải|bắt buộc"
        - "không được"
        - "có trách nhiệm"
        - "được quyền"

  list:
    - type: numbered_item
      preserve_hierarchy: true
      max_depth: 4  # Support deeply nested regulations

# Relationship patterns
relationship_patterns:
  - name: article_reference
    pattern: "Điều\\s+\\d+"
    type: reference
    description: "References to other articles"

  - name: clause_reference
    pattern: "Khoản\\s+\\d+(?:\\s+Điều\\s+\\d+)?"
    type: reference
    description: "References to specific clauses"

  - name: point_reference
    pattern: "Điểm\\s+[a-z](?:\\s+Khoản\\s+\\d+)?(?:\\s+Điều\\s+\\d+)?"
    type: reference
    description: "References to specific points"

  - name: legal_document_reference
    pattern: "(?:Luật|Nghị định|Thông tư|Quyết định)\\s+(?:số\\s+)?\\d+[/-]\\d+(?:[/-][A-Z]+)?"
    type: reference
    description: "References to other legal documents"

  - name: amendment_reference
    pattern: "(?:sửa đổi|bổ sung|thay thế).*(?:theo|tại).*(?:Điều|Nghị định|Thông tư)\\s+\\d+"
    type: amendment
    description: "Amendment information"

  - name: implementation_reference
    pattern: "thực hiện theo.*(?:Điều|Mục|Chương)\\s+\\d+"
    type: prerequisite
    description: "Implementation prerequisites"

# Metadata extractors
metadata_extractors:
  article_number:
    pattern: "Điều\\s+(\\d+)"
    extract: "number"

  chapter_number:
    pattern: "Chương\\s+([IVX]+|\\d+)"
    extract: "number"

  effective_date:
    patterns:
      - "có hiệu lực từ(?:\\s+ngày)?\\s+(\\d{1,2}[/-]\\d{1,2}[/-]\\d{4})"
      - "thi hành từ(?:\\s+ngày)?\\s+(\\d{1,2}[/-]\\d{1,2}[/-]\\d{4})"
    format: "DD/MM/YYYY"

  authority:
    patterns:
      - "Bộ\\s+[A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴỶỸ][a-zàáâãèéêìíòóôõùúăđĩũơưăạảấầẩẫậắằẳẵặẹẻẽềềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ\\s]+"
      - "(?:Thủ tướng|Chính phủ|Quốc hội)"

  scope:
    keywords:
      - "toàn quốc"
      - "địa phương"
      - "thành phố"
      - "tỉnh"
      - "khu vực"

  obligation_level:
    keywords:
      mandatory:
        - "phải"
        - "bắt buộc"
        - "cần thiết"
      prohibited:
        - "không được"
        - "cấm"
        - "nghiêm cấm"
      permitted:
        - "được phép"
        - "có thể"
        - "được quyền"

# Chunk size constraints
first_level_min_tokens: 1200
first_level_max_tokens: 2500
second_level_min_tokens: 400
second_level_max_tokens: 1200

# Vietnamese legal document settings
language_settings:
  tokenizer: "underthesea"
  preserve_tone_marks: true
  recognize_abbreviations:
    - "TT"   # Thông tư
    - "NĐ"   # Nghị định
    - "QĐ"   # Quyết định
    - "LĐ"   # Luật định
    - "CP"   # Chính phủ
    - "TTg"  # Thủ tướng
  legal_structure_markers:
    - "Chương"
    - "Mục"
    - "Điều"
    - "Khoản"
    - "Điểm"
